version: '3.4'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: password
      #MYSQL_ALLOW_EMPTY_PASSWORD: yes
      #MYSQL_USER: user
      #MYSQL_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/init/db:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
